conexao(a, b).
conexao(a, d).
conexao(a, f).
conexao(a, m).
conexao(b, c).
conexao(b, e).
conexao(b, v).
conexao(d, i).
conexao(d, j).
conexao(f, g).
conexao(f, h).
conexao(m, n).
conexao(m, o).
conexao(i, y).
conexao(j, k).
conexao(j, l).
conexao(n, q).
conexao(n, p).
conexao(k, t).
conexao(k, u).
conexao(q, r).
conexao(q, s).
conexao(r, w).
conexao(s, x).